//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGUI.ServiceRecipeRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRecipeRef.IRecipeLibrary")]
    public interface IRecipeLibrary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeLibrary/FetchMealsData", ReplyAction="http://tempuri.org/IRecipeLibrary/FetchMealsDataResponse")]
        MealsLibrary1.Recipe[] FetchMealsData(string meal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeLibrary/FetchMealsData", ReplyAction="http://tempuri.org/IRecipeLibrary/FetchMealsDataResponse")]
        System.Threading.Tasks.Task<MealsLibrary1.Recipe[]> FetchMealsDataAsync(string meal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeLibrary/AddMealToSaved", ReplyAction="http://tempuri.org/IRecipeLibrary/AddMealToSavedResponse")]
        void AddMealToSaved(MealsLibrary1.Recipe recipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeLibrary/AddMealToSaved", ReplyAction="http://tempuri.org/IRecipeLibrary/AddMealToSavedResponse")]
        System.Threading.Tasks.Task AddMealToSavedAsync(MealsLibrary1.Recipe recipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeLibrary/RemoveMealFromSaved", ReplyAction="http://tempuri.org/IRecipeLibrary/RemoveMealFromSavedResponse")]
        void RemoveMealFromSaved(string idMeal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeLibrary/RemoveMealFromSaved", ReplyAction="http://tempuri.org/IRecipeLibrary/RemoveMealFromSavedResponse")]
        System.Threading.Tasks.Task RemoveMealFromSavedAsync(string idMeal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeLibrary/GetAllSavedRecipes", ReplyAction="http://tempuri.org/IRecipeLibrary/GetAllSavedRecipesResponse")]
        MealsLibrary1.Recipe[] GetAllSavedRecipes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeLibrary/GetAllSavedRecipes", ReplyAction="http://tempuri.org/IRecipeLibrary/GetAllSavedRecipesResponse")]
        System.Threading.Tasks.Task<MealsLibrary1.Recipe[]> GetAllSavedRecipesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecipeLibraryChannel : AppGUI.ServiceRecipeRef.IRecipeLibrary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecipeLibraryClient : System.ServiceModel.ClientBase<AppGUI.ServiceRecipeRef.IRecipeLibrary>, AppGUI.ServiceRecipeRef.IRecipeLibrary {
        
        public RecipeLibraryClient() {
        }
        
        public RecipeLibraryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecipeLibraryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipeLibraryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipeLibraryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MealsLibrary1.Recipe[] FetchMealsData(string meal) {
            return base.Channel.FetchMealsData(meal);
        }
        
        public System.Threading.Tasks.Task<MealsLibrary1.Recipe[]> FetchMealsDataAsync(string meal) {
            return base.Channel.FetchMealsDataAsync(meal);
        }
        
        public void AddMealToSaved(MealsLibrary1.Recipe recipe) {
            base.Channel.AddMealToSaved(recipe);
        }
        
        public System.Threading.Tasks.Task AddMealToSavedAsync(MealsLibrary1.Recipe recipe) {
            return base.Channel.AddMealToSavedAsync(recipe);
        }
        
        public void RemoveMealFromSaved(string idMeal) {
            base.Channel.RemoveMealFromSaved(idMeal);
        }
        
        public System.Threading.Tasks.Task RemoveMealFromSavedAsync(string idMeal) {
            return base.Channel.RemoveMealFromSavedAsync(idMeal);
        }
        
        public MealsLibrary1.Recipe[] GetAllSavedRecipes() {
            return base.Channel.GetAllSavedRecipes();
        }
        
        public System.Threading.Tasks.Task<MealsLibrary1.Recipe[]> GetAllSavedRecipesAsync() {
            return base.Channel.GetAllSavedRecipesAsync();
        }
    }
}
