//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGUI.ServiceRef1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipe", Namespace="http://schemas.datacontract.org/2004/07/MealsLibrary1")]
    [System.SerializableAttribute()]
    public partial class Recipe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string areaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idMealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instructionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sourceUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string youtubeUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string area {
            get {
                return this.areaField;
            }
            set {
                if ((object.ReferenceEquals(this.areaField, value) != true)) {
                    this.areaField = value;
                    this.RaisePropertyChanged("area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idMeal {
            get {
                return this.idMealField;
            }
            set {
                if ((object.ReferenceEquals(this.idMealField, value) != true)) {
                    this.idMealField = value;
                    this.RaisePropertyChanged("idMeal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.imageUrlField, value) != true)) {
                    this.imageUrlField = value;
                    this.RaisePropertyChanged("imageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instructions {
            get {
                return this.instructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.instructionsField, value) != true)) {
                    this.instructionsField = value;
                    this.RaisePropertyChanged("instructions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sourceUrl {
            get {
                return this.sourceUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.sourceUrlField, value) != true)) {
                    this.sourceUrlField = value;
                    this.RaisePropertyChanged("sourceUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string youtubeUrl {
            get {
                return this.youtubeUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.youtubeUrlField, value) != true)) {
                    this.youtubeUrlField = value;
                    this.RaisePropertyChanged("youtubeUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef1.IRecipeLibrary")]
    public interface IRecipeLibrary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeLibrary/FetchMealsData", ReplyAction="http://tempuri.org/IRecipeLibrary/FetchMealsDataResponse")]
        AppGUI.ServiceRef1.Recipe[] FetchMealsData(string meal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeLibrary/FetchMealsData", ReplyAction="http://tempuri.org/IRecipeLibrary/FetchMealsDataResponse")]
        System.Threading.Tasks.Task<AppGUI.ServiceRef1.Recipe[]> FetchMealsDataAsync(string meal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecipeLibraryChannel : AppGUI.ServiceRef1.IRecipeLibrary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecipeLibraryClient : System.ServiceModel.ClientBase<AppGUI.ServiceRef1.IRecipeLibrary>, AppGUI.ServiceRef1.IRecipeLibrary {
        
        public RecipeLibraryClient() {
        }
        
        public RecipeLibraryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecipeLibraryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipeLibraryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipeLibraryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppGUI.ServiceRef1.Recipe[] FetchMealsData(string meal) {
            return base.Channel.FetchMealsData(meal);
        }
        
        public System.Threading.Tasks.Task<AppGUI.ServiceRef1.Recipe[]> FetchMealsDataAsync(string meal) {
            return base.Channel.FetchMealsDataAsync(meal);
        }
    }
}
